### ISSUE TITLE
Dashboard > Adjust column width to its content to prevent line break

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#237]
![image](https://cloud.githubusercontent.com/assets/1778633/10512165/8df950a6-7368-11e5-8dce-a6dd5746c919.png)

We need to find a clever way to adjust the width of the `Ticket ID` column to its content. Perhaps we can programmatically get the max of amount of characters of a ticket ID, and adjust the size accordingly.

What do you think @julien731 ?

This issue is closely related to the UX/UI improvements of #197

**Comment by SiamKreative** [comment]
```css
.column-status {
	width: 90px !important;
	overflow: hidden
}
.column-ticket_id {
	width: 50px !important;
	overflow: hidden
}
```

The same issue goes for the __Status Column__. For example, if the translation in an other language is much longer...
